[project]
name = "shrinking-bert"
version = "0.1.0"
description = "Exploring model compression techniques using BERT for NER task"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit==4.6.2",
    "ruff==0.16.8",
    "ty==0.0.82",
]

[tool.uv]
package = true

[tool.setuptools]
packages = ["src"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff]
line-length = 100
